version: '3'
services:
  webserver:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - database
      - cache
    networks:
      - laravel_network

  database:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - laravel_network
    ports:
      - "${FORWARD_DB_PORT}:3306"

  cache:
    image: redis:latest
    volumes:
      - ./redis-data:/data
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge