version: '3'
services:
  webserver:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - '${APP_PORT}:80'
    networks:
      - quran_complex

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - database
      - cache
    networks:
      - quran_complex

  database:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    networks:
      - quran_complex
    ports:
      - "${DB_PORT}:3306"

  cache:
    image: redis:latest
    volumes:
      - ./docker/redis-data:/data
    networks:
      - quran_complex

networks:
  quran_complex:
    driver: bridge